site_name: Minha jornada de aprendizado em arquitetura de software
site_description: Meus fichamentos sobre minhas leituras e projetos da minha jornada de aprendizado
site_author: Aline Oliveira

# config do tema
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightnrdd-7
        name: mudar para modo escuro
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: mudar para modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy

plugins:
  - search
markdown_extensions:
  - pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Início: index.md
  - Ementa: ementa.md
